/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.driver.model.cap;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Certainty {
  Observed, Likely, Possible, Unlikely, Unknown  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Certainty\",\"namespace\":\"eu.driver.model.cap\",\"symbols\":[\"Observed\",\"Likely\",\"Possible\",\"Unlikely\",\"Unknown\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
