/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.driver.model.cap;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class publishedAllowed extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6304027057797238260L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"publishedAllowed\",\"namespace\":\"eu.driver.model.cap\",\"fields\":[{\"name\":\"id\",\"type\":\"string\",\"doc\":\"sender Client id\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<publishedAllowed> ENCODER =
      new BinaryMessageEncoder<publishedAllowed>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<publishedAllowed> DECODER =
      new BinaryMessageDecoder<publishedAllowed>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<publishedAllowed> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<publishedAllowed> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<publishedAllowed>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this publishedAllowed to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a publishedAllowed from a ByteBuffer. */
  public static publishedAllowed fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** sender Client id */
  @Deprecated public java.lang.CharSequence id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public publishedAllowed() {}

  /**
   * All-args constructor.
   * @param id sender Client id
   */
  public publishedAllowed(java.lang.CharSequence id) {
    this.id = id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return sender Client id
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * sender Client id
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Creates a new publishedAllowed RecordBuilder.
   * @return A new publishedAllowed RecordBuilder
   */
  public static eu.driver.model.cap.publishedAllowed.Builder newBuilder() {
    return new eu.driver.model.cap.publishedAllowed.Builder();
  }

  /**
   * Creates a new publishedAllowed RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new publishedAllowed RecordBuilder
   */
  public static eu.driver.model.cap.publishedAllowed.Builder newBuilder(eu.driver.model.cap.publishedAllowed.Builder other) {
    return new eu.driver.model.cap.publishedAllowed.Builder(other);
  }

  /**
   * Creates a new publishedAllowed RecordBuilder by copying an existing publishedAllowed instance.
   * @param other The existing instance to copy.
   * @return A new publishedAllowed RecordBuilder
   */
  public static eu.driver.model.cap.publishedAllowed.Builder newBuilder(eu.driver.model.cap.publishedAllowed other) {
    return new eu.driver.model.cap.publishedAllowed.Builder(other);
  }

  /**
   * RecordBuilder for publishedAllowed instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<publishedAllowed>
    implements org.apache.avro.data.RecordBuilder<publishedAllowed> {

    /** sender Client id */
    private java.lang.CharSequence id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eu.driver.model.cap.publishedAllowed.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing publishedAllowed instance
     * @param other The existing instance to copy.
     */
    private Builder(eu.driver.model.cap.publishedAllowed other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * sender Client id
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * sender Client id
      * @param value The value of 'id'.
      * @return This builder.
      */
    public eu.driver.model.cap.publishedAllowed.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * sender Client id
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * sender Client id
      * @return This builder.
      */
    public eu.driver.model.cap.publishedAllowed.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public publishedAllowed build() {
      try {
        publishedAllowed record = new publishedAllowed();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<publishedAllowed>
    WRITER$ = (org.apache.avro.io.DatumWriter<publishedAllowed>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<publishedAllowed>
    READER$ = (org.apache.avro.io.DatumReader<publishedAllowed>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
