/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.driver.model.cap;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Status {
  Actual, Exercise, System, Test, Draft  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Status\",\"namespace\":\"eu.driver.model.cap\",\"symbols\":[\"Actual\",\"Exercise\",\"System\",\"Test\",\"Draft\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
