/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.driver.model.cap;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ValueNamePair extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1172076063959943070L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ValueNamePair\",\"namespace\":\"eu.driver.model.cap\",\"fields\":[{\"name\":\"valueName\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ValueNamePair> ENCODER =
      new BinaryMessageEncoder<ValueNamePair>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ValueNamePair> DECODER =
      new BinaryMessageDecoder<ValueNamePair>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ValueNamePair> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ValueNamePair> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ValueNamePair>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ValueNamePair to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ValueNamePair from a ByteBuffer. */
  public static ValueNamePair fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence valueName;
  @Deprecated public java.lang.CharSequence value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ValueNamePair() {}

  /**
   * All-args constructor.
   * @param valueName The new value for valueName
   * @param value The new value for value
   */
  public ValueNamePair(java.lang.CharSequence valueName, java.lang.CharSequence value) {
    this.valueName = valueName;
    this.value = value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return valueName;
    case 1: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: valueName = (java.lang.CharSequence)value$; break;
    case 1: value = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'valueName' field.
   * @return The value of the 'valueName' field.
   */
  public java.lang.CharSequence getValueName() {
    return valueName;
  }

  /**
   * Sets the value of the 'valueName' field.
   * @param value the value to set.
   */
  public void setValueName(java.lang.CharSequence value) {
    this.valueName = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.lang.CharSequence getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.CharSequence value) {
    this.value = value;
  }

  /**
   * Creates a new ValueNamePair RecordBuilder.
   * @return A new ValueNamePair RecordBuilder
   */
  public static eu.driver.model.cap.ValueNamePair.Builder newBuilder() {
    return new eu.driver.model.cap.ValueNamePair.Builder();
  }

  /**
   * Creates a new ValueNamePair RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ValueNamePair RecordBuilder
   */
  public static eu.driver.model.cap.ValueNamePair.Builder newBuilder(eu.driver.model.cap.ValueNamePair.Builder other) {
    return new eu.driver.model.cap.ValueNamePair.Builder(other);
  }

  /**
   * Creates a new ValueNamePair RecordBuilder by copying an existing ValueNamePair instance.
   * @param other The existing instance to copy.
   * @return A new ValueNamePair RecordBuilder
   */
  public static eu.driver.model.cap.ValueNamePair.Builder newBuilder(eu.driver.model.cap.ValueNamePair other) {
    return new eu.driver.model.cap.ValueNamePair.Builder(other);
  }

  /**
   * RecordBuilder for ValueNamePair instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ValueNamePair>
    implements org.apache.avro.data.RecordBuilder<ValueNamePair> {

    private java.lang.CharSequence valueName;
    private java.lang.CharSequence value;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eu.driver.model.cap.ValueNamePair.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.valueName)) {
        this.valueName = data().deepCopy(fields()[0].schema(), other.valueName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ValueNamePair instance
     * @param other The existing instance to copy.
     */
    private Builder(eu.driver.model.cap.ValueNamePair other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.valueName)) {
        this.valueName = data().deepCopy(fields()[0].schema(), other.valueName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'valueName' field.
      * @return The value.
      */
    public java.lang.CharSequence getValueName() {
      return valueName;
    }

    /**
      * Sets the value of the 'valueName' field.
      * @param value The value of 'valueName'.
      * @return This builder.
      */
    public eu.driver.model.cap.ValueNamePair.Builder setValueName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.valueName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'valueName' field has been set.
      * @return True if the 'valueName' field has been set, false otherwise.
      */
    public boolean hasValueName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'valueName' field.
      * @return This builder.
      */
    public eu.driver.model.cap.ValueNamePair.Builder clearValueName() {
      valueName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.lang.CharSequence getValue() {
      return value;
    }

    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public eu.driver.model.cap.ValueNamePair.Builder setValue(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public eu.driver.model.cap.ValueNamePair.Builder clearValue() {
      value = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ValueNamePair build() {
      try {
        ValueNamePair record = new ValueNamePair();
        record.valueName = fieldSetFlags()[0] ? this.valueName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.value = fieldSetFlags()[1] ? this.value : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ValueNamePair>
    WRITER$ = (org.apache.avro.io.DatumWriter<ValueNamePair>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ValueNamePair>
    READER$ = (org.apache.avro.io.DatumReader<ValueNamePair>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
