/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.driver.model.mlp;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AltAcc extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5658029796028909817L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AltAcc\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[{\"name\":\"alt_acc\",\"type\":[\"null\",\"int\"],\"doc\":\"Accuracy of Altitude in meters\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AltAcc> ENCODER =
      new BinaryMessageEncoder<AltAcc>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AltAcc> DECODER =
      new BinaryMessageDecoder<AltAcc>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AltAcc> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AltAcc> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AltAcc>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AltAcc to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AltAcc from a ByteBuffer. */
  public static AltAcc fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Accuracy of Altitude in meters */
  @Deprecated public java.lang.Integer alt_acc;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AltAcc() {}

  /**
   * All-args constructor.
   * @param alt_acc Accuracy of Altitude in meters
   */
  public AltAcc(java.lang.Integer alt_acc) {
    this.alt_acc = alt_acc;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return alt_acc;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: alt_acc = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'alt_acc' field.
   * @return Accuracy of Altitude in meters
   */
  public java.lang.Integer getAltAcc() {
    return alt_acc;
  }

  /**
   * Sets the value of the 'alt_acc' field.
   * Accuracy of Altitude in meters
   * @param value the value to set.
   */
  public void setAltAcc(java.lang.Integer value) {
    this.alt_acc = value;
  }

  /**
   * Creates a new AltAcc RecordBuilder.
   * @return A new AltAcc RecordBuilder
   */
  public static eu.driver.model.mlp.AltAcc.Builder newBuilder() {
    return new eu.driver.model.mlp.AltAcc.Builder();
  }

  /**
   * Creates a new AltAcc RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AltAcc RecordBuilder
   */
  public static eu.driver.model.mlp.AltAcc.Builder newBuilder(eu.driver.model.mlp.AltAcc.Builder other) {
    return new eu.driver.model.mlp.AltAcc.Builder(other);
  }

  /**
   * Creates a new AltAcc RecordBuilder by copying an existing AltAcc instance.
   * @param other The existing instance to copy.
   * @return A new AltAcc RecordBuilder
   */
  public static eu.driver.model.mlp.AltAcc.Builder newBuilder(eu.driver.model.mlp.AltAcc other) {
    return new eu.driver.model.mlp.AltAcc.Builder(other);
  }

  /**
   * RecordBuilder for AltAcc instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AltAcc>
    implements org.apache.avro.data.RecordBuilder<AltAcc> {

    /** Accuracy of Altitude in meters */
    private java.lang.Integer alt_acc;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eu.driver.model.mlp.AltAcc.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.alt_acc)) {
        this.alt_acc = data().deepCopy(fields()[0].schema(), other.alt_acc);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AltAcc instance
     * @param other The existing instance to copy.
     */
    private Builder(eu.driver.model.mlp.AltAcc other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.alt_acc)) {
        this.alt_acc = data().deepCopy(fields()[0].schema(), other.alt_acc);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'alt_acc' field.
      * Accuracy of Altitude in meters
      * @return The value.
      */
    public java.lang.Integer getAltAcc() {
      return alt_acc;
    }

    /**
      * Sets the value of the 'alt_acc' field.
      * Accuracy of Altitude in meters
      * @param value The value of 'alt_acc'.
      * @return This builder.
      */
    public eu.driver.model.mlp.AltAcc.Builder setAltAcc(java.lang.Integer value) {
      validate(fields()[0], value);
      this.alt_acc = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'alt_acc' field has been set.
      * Accuracy of Altitude in meters
      * @return True if the 'alt_acc' field has been set, false otherwise.
      */
    public boolean hasAltAcc() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'alt_acc' field.
      * Accuracy of Altitude in meters
      * @return This builder.
      */
    public eu.driver.model.mlp.AltAcc.Builder clearAltAcc() {
      alt_acc = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AltAcc build() {
      try {
        AltAcc record = new AltAcc();
        record.alt_acc = fieldSetFlags()[0] ? this.alt_acc : (java.lang.Integer) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AltAcc>
    WRITER$ = (org.apache.avro.io.DatumWriter<AltAcc>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AltAcc>
    READER$ = (org.apache.avro.io.DatumReader<AltAcc>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
