/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.driver.model.mlp;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum AttrType {
  MSISDN, IMSI, IMEI, MIN, MDN, EME_MSID, ASID, OPE_ID, IPV4, IPV6, SESSID  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AttrType\",\"namespace\":\"eu.driver.model.mlp\",\"symbols\":[\"MSISDN\",\"IMSI\",\"IMEI\",\"MIN\",\"MDN\",\"EME_MSID\",\"ASID\",\"OPE_ID\",\"IPV4\",\"IPV6\",\"SESSID\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
