/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.driver.model.sim;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Special message to indicate a particular entity/connection has been deleted. *Copyright (C) 2017-2018 XVR Simulation B.V., Delft, The Netherlands, Martijn Hendriks <hendriks @ xvrsim.com>. This file is part of DRIVER+ WP923 Test-bed infrastructure project. This file is licensed under the MIT license : https://github.com/DRIVER-EU/avro-schemas/blob/master/LICENSE* */
@org.apache.avro.specific.AvroGenerated
public class ObjectDeleted extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8182547914189512379L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ObjectDeleted\",\"namespace\":\"eu.driver.model.sim\",\"doc\":\"Special message to indicate a particular entity/connection has been deleted. *Copyright (C) 2017-2018 XVR Simulation B.V., Delft, The Netherlands, Martijn Hendriks <hendriks @ xvrsim.com>. This file is part of DRIVER+ WP923 Test-bed infrastructure project. This file is licensed under the MIT license : https://github.com/DRIVER-EU/avro-schemas/blob/master/LICENSE*\",\"fields\":[{\"name\":\"guid\",\"type\":\"string\",\"doc\":\"globally unique identifier for the entity/connection that is deleted\"},{\"name\":\"owner\",\"type\":\"string\",\"doc\":\"identifier of the simulator currently responsible for this entity/connection\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ObjectDeleted> ENCODER =
      new BinaryMessageEncoder<ObjectDeleted>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ObjectDeleted> DECODER =
      new BinaryMessageDecoder<ObjectDeleted>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ObjectDeleted> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ObjectDeleted> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ObjectDeleted>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ObjectDeleted to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ObjectDeleted from a ByteBuffer. */
  public static ObjectDeleted fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** globally unique identifier for the entity/connection that is deleted */
  @Deprecated public java.lang.CharSequence guid;
  /** identifier of the simulator currently responsible for this entity/connection */
  @Deprecated public java.lang.CharSequence owner;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ObjectDeleted() {}

  /**
   * All-args constructor.
   * @param guid globally unique identifier for the entity/connection that is deleted
   * @param owner identifier of the simulator currently responsible for this entity/connection
   */
  public ObjectDeleted(java.lang.CharSequence guid, java.lang.CharSequence owner) {
    this.guid = guid;
    this.owner = owner;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return guid;
    case 1: return owner;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: guid = (java.lang.CharSequence)value$; break;
    case 1: owner = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'guid' field.
   * @return globally unique identifier for the entity/connection that is deleted
   */
  public java.lang.CharSequence getGuid() {
    return guid;
  }

  /**
   * Sets the value of the 'guid' field.
   * globally unique identifier for the entity/connection that is deleted
   * @param value the value to set.
   */
  public void setGuid(java.lang.CharSequence value) {
    this.guid = value;
  }

  /**
   * Gets the value of the 'owner' field.
   * @return identifier of the simulator currently responsible for this entity/connection
   */
  public java.lang.CharSequence getOwner() {
    return owner;
  }

  /**
   * Sets the value of the 'owner' field.
   * identifier of the simulator currently responsible for this entity/connection
   * @param value the value to set.
   */
  public void setOwner(java.lang.CharSequence value) {
    this.owner = value;
  }

  /**
   * Creates a new ObjectDeleted RecordBuilder.
   * @return A new ObjectDeleted RecordBuilder
   */
  public static eu.driver.model.sim.ObjectDeleted.Builder newBuilder() {
    return new eu.driver.model.sim.ObjectDeleted.Builder();
  }

  /**
   * Creates a new ObjectDeleted RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ObjectDeleted RecordBuilder
   */
  public static eu.driver.model.sim.ObjectDeleted.Builder newBuilder(eu.driver.model.sim.ObjectDeleted.Builder other) {
    return new eu.driver.model.sim.ObjectDeleted.Builder(other);
  }

  /**
   * Creates a new ObjectDeleted RecordBuilder by copying an existing ObjectDeleted instance.
   * @param other The existing instance to copy.
   * @return A new ObjectDeleted RecordBuilder
   */
  public static eu.driver.model.sim.ObjectDeleted.Builder newBuilder(eu.driver.model.sim.ObjectDeleted other) {
    return new eu.driver.model.sim.ObjectDeleted.Builder(other);
  }

  /**
   * RecordBuilder for ObjectDeleted instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ObjectDeleted>
    implements org.apache.avro.data.RecordBuilder<ObjectDeleted> {

    /** globally unique identifier for the entity/connection that is deleted */
    private java.lang.CharSequence guid;
    /** identifier of the simulator currently responsible for this entity/connection */
    private java.lang.CharSequence owner;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eu.driver.model.sim.ObjectDeleted.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.guid)) {
        this.guid = data().deepCopy(fields()[0].schema(), other.guid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.owner)) {
        this.owner = data().deepCopy(fields()[1].schema(), other.owner);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ObjectDeleted instance
     * @param other The existing instance to copy.
     */
    private Builder(eu.driver.model.sim.ObjectDeleted other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.guid)) {
        this.guid = data().deepCopy(fields()[0].schema(), other.guid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.owner)) {
        this.owner = data().deepCopy(fields()[1].schema(), other.owner);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'guid' field.
      * globally unique identifier for the entity/connection that is deleted
      * @return The value.
      */
    public java.lang.CharSequence getGuid() {
      return guid;
    }

    /**
      * Sets the value of the 'guid' field.
      * globally unique identifier for the entity/connection that is deleted
      * @param value The value of 'guid'.
      * @return This builder.
      */
    public eu.driver.model.sim.ObjectDeleted.Builder setGuid(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.guid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'guid' field has been set.
      * globally unique identifier for the entity/connection that is deleted
      * @return True if the 'guid' field has been set, false otherwise.
      */
    public boolean hasGuid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'guid' field.
      * globally unique identifier for the entity/connection that is deleted
      * @return This builder.
      */
    public eu.driver.model.sim.ObjectDeleted.Builder clearGuid() {
      guid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'owner' field.
      * identifier of the simulator currently responsible for this entity/connection
      * @return The value.
      */
    public java.lang.CharSequence getOwner() {
      return owner;
    }

    /**
      * Sets the value of the 'owner' field.
      * identifier of the simulator currently responsible for this entity/connection
      * @param value The value of 'owner'.
      * @return This builder.
      */
    public eu.driver.model.sim.ObjectDeleted.Builder setOwner(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.owner = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'owner' field has been set.
      * identifier of the simulator currently responsible for this entity/connection
      * @return True if the 'owner' field has been set, false otherwise.
      */
    public boolean hasOwner() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'owner' field.
      * identifier of the simulator currently responsible for this entity/connection
      * @return This builder.
      */
    public eu.driver.model.sim.ObjectDeleted.Builder clearOwner() {
      owner = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ObjectDeleted build() {
      try {
        ObjectDeleted record = new ObjectDeleted();
        record.guid = fieldSetFlags()[0] ? this.guid : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.owner = fieldSetFlags()[1] ? this.owner : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ObjectDeleted>
    WRITER$ = (org.apache.avro.io.DatumWriter<ObjectDeleted>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ObjectDeleted>
    READER$ = (org.apache.avro.io.DatumReader<ObjectDeleted>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
