/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.driver.model.geojson.sim;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum LabelEnum {
  POLICE, MEDICAL, FIRE, MILITARY, SECURITY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"LabelEnum\",\"namespace\":\"eu.driver.model.geojson.sim\",\"symbols\":[\"POLICE\",\"MEDICAL\",\"FIRE\",\"MILITARY\",\"SECURITY\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
