/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.driver.model.geojson.sim;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum LineStringType {
  LineString  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"LineStringType\",\"namespace\":\"eu.driver.model.geojson.sim\",\"symbols\":[\"LineString\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
