/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.driver.model.sim.request;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Request for starting a simulation inject. *Copyright (C) 2017-2018 XVR Simulation B.V., Delft, The Netherlands, Martijn Hendriks <hendriks @ xvrsim.com>. This file is part of DRIVER+ WP923 Test-bed infrastructure project. This file is licensed under the MIT license : https://github.com/DRIVER-EU/avro-schemas/blob/master/LICENSE* */
@org.apache.avro.specific.AvroGenerated
public class RequestStartInject extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8920595315635555871L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RequestStartInject\",\"namespace\":\"eu.driver.model.sim.request\",\"doc\":\"Request for starting a simulation inject. *Copyright (C) 2017-2018 XVR Simulation B.V., Delft, The Netherlands, Martijn Hendriks <hendriks @ xvrsim.com>. This file is part of DRIVER+ WP923 Test-bed infrastructure project. This file is licensed under the MIT license : https://github.com/DRIVER-EU/avro-schemas/blob/master/LICENSE*\",\"fields\":[{\"name\":\"guid\",\"type\":\"string\",\"doc\":\"Globally unique identifier for this request\"},{\"name\":\"owner\",\"type\":\"string\",\"doc\":\"Identifier of the simulator currently responsible for this request\"},{\"name\":\"inject\",\"type\":\"string\",\"doc\":\"Name of the inject that needs to be started\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RequestStartInject> ENCODER =
      new BinaryMessageEncoder<RequestStartInject>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RequestStartInject> DECODER =
      new BinaryMessageDecoder<RequestStartInject>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<RequestStartInject> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<RequestStartInject> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RequestStartInject>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this RequestStartInject to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a RequestStartInject from a ByteBuffer. */
  public static RequestStartInject fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Globally unique identifier for this request */
  @Deprecated public java.lang.CharSequence guid;
  /** Identifier of the simulator currently responsible for this request */
  @Deprecated public java.lang.CharSequence owner;
  /** Name of the inject that needs to be started */
  @Deprecated public java.lang.CharSequence inject;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RequestStartInject() {}

  /**
   * All-args constructor.
   * @param guid Globally unique identifier for this request
   * @param owner Identifier of the simulator currently responsible for this request
   * @param inject Name of the inject that needs to be started
   */
  public RequestStartInject(java.lang.CharSequence guid, java.lang.CharSequence owner, java.lang.CharSequence inject) {
    this.guid = guid;
    this.owner = owner;
    this.inject = inject;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return guid;
    case 1: return owner;
    case 2: return inject;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: guid = (java.lang.CharSequence)value$; break;
    case 1: owner = (java.lang.CharSequence)value$; break;
    case 2: inject = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'guid' field.
   * @return Globally unique identifier for this request
   */
  public java.lang.CharSequence getGuid() {
    return guid;
  }

  /**
   * Sets the value of the 'guid' field.
   * Globally unique identifier for this request
   * @param value the value to set.
   */
  public void setGuid(java.lang.CharSequence value) {
    this.guid = value;
  }

  /**
   * Gets the value of the 'owner' field.
   * @return Identifier of the simulator currently responsible for this request
   */
  public java.lang.CharSequence getOwner() {
    return owner;
  }

  /**
   * Sets the value of the 'owner' field.
   * Identifier of the simulator currently responsible for this request
   * @param value the value to set.
   */
  public void setOwner(java.lang.CharSequence value) {
    this.owner = value;
  }

  /**
   * Gets the value of the 'inject' field.
   * @return Name of the inject that needs to be started
   */
  public java.lang.CharSequence getInject() {
    return inject;
  }

  /**
   * Sets the value of the 'inject' field.
   * Name of the inject that needs to be started
   * @param value the value to set.
   */
  public void setInject(java.lang.CharSequence value) {
    this.inject = value;
  }

  /**
   * Creates a new RequestStartInject RecordBuilder.
   * @return A new RequestStartInject RecordBuilder
   */
  public static eu.driver.model.sim.request.RequestStartInject.Builder newBuilder() {
    return new eu.driver.model.sim.request.RequestStartInject.Builder();
  }

  /**
   * Creates a new RequestStartInject RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RequestStartInject RecordBuilder
   */
  public static eu.driver.model.sim.request.RequestStartInject.Builder newBuilder(eu.driver.model.sim.request.RequestStartInject.Builder other) {
    return new eu.driver.model.sim.request.RequestStartInject.Builder(other);
  }

  /**
   * Creates a new RequestStartInject RecordBuilder by copying an existing RequestStartInject instance.
   * @param other The existing instance to copy.
   * @return A new RequestStartInject RecordBuilder
   */
  public static eu.driver.model.sim.request.RequestStartInject.Builder newBuilder(eu.driver.model.sim.request.RequestStartInject other) {
    return new eu.driver.model.sim.request.RequestStartInject.Builder(other);
  }

  /**
   * RecordBuilder for RequestStartInject instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RequestStartInject>
    implements org.apache.avro.data.RecordBuilder<RequestStartInject> {

    /** Globally unique identifier for this request */
    private java.lang.CharSequence guid;
    /** Identifier of the simulator currently responsible for this request */
    private java.lang.CharSequence owner;
    /** Name of the inject that needs to be started */
    private java.lang.CharSequence inject;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eu.driver.model.sim.request.RequestStartInject.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.guid)) {
        this.guid = data().deepCopy(fields()[0].schema(), other.guid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.owner)) {
        this.owner = data().deepCopy(fields()[1].schema(), other.owner);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.inject)) {
        this.inject = data().deepCopy(fields()[2].schema(), other.inject);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing RequestStartInject instance
     * @param other The existing instance to copy.
     */
    private Builder(eu.driver.model.sim.request.RequestStartInject other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.guid)) {
        this.guid = data().deepCopy(fields()[0].schema(), other.guid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.owner)) {
        this.owner = data().deepCopy(fields()[1].schema(), other.owner);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.inject)) {
        this.inject = data().deepCopy(fields()[2].schema(), other.inject);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'guid' field.
      * Globally unique identifier for this request
      * @return The value.
      */
    public java.lang.CharSequence getGuid() {
      return guid;
    }

    /**
      * Sets the value of the 'guid' field.
      * Globally unique identifier for this request
      * @param value The value of 'guid'.
      * @return This builder.
      */
    public eu.driver.model.sim.request.RequestStartInject.Builder setGuid(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.guid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'guid' field has been set.
      * Globally unique identifier for this request
      * @return True if the 'guid' field has been set, false otherwise.
      */
    public boolean hasGuid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'guid' field.
      * Globally unique identifier for this request
      * @return This builder.
      */
    public eu.driver.model.sim.request.RequestStartInject.Builder clearGuid() {
      guid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'owner' field.
      * Identifier of the simulator currently responsible for this request
      * @return The value.
      */
    public java.lang.CharSequence getOwner() {
      return owner;
    }

    /**
      * Sets the value of the 'owner' field.
      * Identifier of the simulator currently responsible for this request
      * @param value The value of 'owner'.
      * @return This builder.
      */
    public eu.driver.model.sim.request.RequestStartInject.Builder setOwner(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.owner = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'owner' field has been set.
      * Identifier of the simulator currently responsible for this request
      * @return True if the 'owner' field has been set, false otherwise.
      */
    public boolean hasOwner() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'owner' field.
      * Identifier of the simulator currently responsible for this request
      * @return This builder.
      */
    public eu.driver.model.sim.request.RequestStartInject.Builder clearOwner() {
      owner = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'inject' field.
      * Name of the inject that needs to be started
      * @return The value.
      */
    public java.lang.CharSequence getInject() {
      return inject;
    }

    /**
      * Sets the value of the 'inject' field.
      * Name of the inject that needs to be started
      * @param value The value of 'inject'.
      * @return This builder.
      */
    public eu.driver.model.sim.request.RequestStartInject.Builder setInject(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.inject = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'inject' field has been set.
      * Name of the inject that needs to be started
      * @return True if the 'inject' field has been set, false otherwise.
      */
    public boolean hasInject() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'inject' field.
      * Name of the inject that needs to be started
      * @return This builder.
      */
    public eu.driver.model.sim.request.RequestStartInject.Builder clearInject() {
      inject = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RequestStartInject build() {
      try {
        RequestStartInject record = new RequestStartInject();
        record.guid = fieldSetFlags()[0] ? this.guid : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.owner = fieldSetFlags()[1] ? this.owner : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.inject = fieldSetFlags()[2] ? this.inject : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RequestStartInject>
    WRITER$ = (org.apache.avro.io.DatumWriter<RequestStartInject>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RequestStartInject>
    READER$ = (org.apache.avro.io.DatumReader<RequestStartInject>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
