/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.driver.model.sim.entity.post;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum MediumTypes {
  CHAT, INCIDENT_REPORT, MAIL, MICROBLOG, NEWS, SITUATION_REPORT, SOCIAL_NETWORK, VIDEO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MediumTypes\",\"namespace\":\"eu.driver.model.sim.entity.post\",\"symbols\":[\"CHAT\",\"INCIDENT_REPORT\",\"MAIL\",\"MICROBLOG\",\"NEWS\",\"SITUATION_REPORT\",\"SOCIAL_NETWORK\",\"VIDEO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
