/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.xvrsim.model.entity.item;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ObjectSubType {
  PROP, TOOL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ObjectSubType\",\"namespace\":\"com.xvrsim.model.entity.item\",\"symbols\":[\"PROP\",\"TOOL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
