/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.driver.model.geojson;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum FeatureType {
  Feature  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FeatureType\",\"namespace\":\"eu.driver.model.geojson\",\"symbols\":[\"Feature\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
