/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.driver.model.geojson;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum PolygonType {
  Polygon  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PolygonType\",\"namespace\":\"eu.driver.model.geojson\",\"symbols\":[\"Polygon\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
