/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.driver.model.core;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** With this message the observer tool gets informed about a new trial state. */
@org.apache.avro.specific.AvroGenerated
public class RequestChangeOfTrialStage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8604299881183289596L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RequestChangeOfTrialStage\",\"namespace\":\"eu.driver.model.core\",\"doc\":\"With this message the observer tool gets informed about a new trial state.\",\"fields\":[{\"name\":\"ostTrialId\",\"type\":[\"null\",\"int\"],\"doc\":\"The unique identifier of the running Trial.\",\"default\":null},{\"name\":\"ostTrialSessionId\",\"type\":\"int\",\"doc\":\"The sessionId for the running Trial.\"},{\"name\":\"ostTrialStageId\",\"type\":\"int\",\"doc\":\"The stageId of the stage that should be activated.\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RequestChangeOfTrialStage> ENCODER =
      new BinaryMessageEncoder<RequestChangeOfTrialStage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RequestChangeOfTrialStage> DECODER =
      new BinaryMessageDecoder<RequestChangeOfTrialStage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<RequestChangeOfTrialStage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<RequestChangeOfTrialStage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RequestChangeOfTrialStage>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this RequestChangeOfTrialStage to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a RequestChangeOfTrialStage from a ByteBuffer. */
  public static RequestChangeOfTrialStage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The unique identifier of the running Trial. */
  @Deprecated public java.lang.Integer ostTrialId;
  /** The sessionId for the running Trial. */
  @Deprecated public int ostTrialSessionId;
  /** The stageId of the stage that should be activated. */
  @Deprecated public int ostTrialStageId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RequestChangeOfTrialStage() {}

  /**
   * All-args constructor.
   * @param ostTrialId The unique identifier of the running Trial.
   * @param ostTrialSessionId The sessionId for the running Trial.
   * @param ostTrialStageId The stageId of the stage that should be activated.
   */
  public RequestChangeOfTrialStage(java.lang.Integer ostTrialId, java.lang.Integer ostTrialSessionId, java.lang.Integer ostTrialStageId) {
    this.ostTrialId = ostTrialId;
    this.ostTrialSessionId = ostTrialSessionId;
    this.ostTrialStageId = ostTrialStageId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ostTrialId;
    case 1: return ostTrialSessionId;
    case 2: return ostTrialStageId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ostTrialId = (java.lang.Integer)value$; break;
    case 1: ostTrialSessionId = (java.lang.Integer)value$; break;
    case 2: ostTrialStageId = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ostTrialId' field.
   * @return The unique identifier of the running Trial.
   */
  public java.lang.Integer getOstTrialId() {
    return ostTrialId;
  }

  /**
   * Sets the value of the 'ostTrialId' field.
   * The unique identifier of the running Trial.
   * @param value the value to set.
   */
  public void setOstTrialId(java.lang.Integer value) {
    this.ostTrialId = value;
  }

  /**
   * Gets the value of the 'ostTrialSessionId' field.
   * @return The sessionId for the running Trial.
   */
  public java.lang.Integer getOstTrialSessionId() {
    return ostTrialSessionId;
  }

  /**
   * Sets the value of the 'ostTrialSessionId' field.
   * The sessionId for the running Trial.
   * @param value the value to set.
   */
  public void setOstTrialSessionId(java.lang.Integer value) {
    this.ostTrialSessionId = value;
  }

  /**
   * Gets the value of the 'ostTrialStageId' field.
   * @return The stageId of the stage that should be activated.
   */
  public java.lang.Integer getOstTrialStageId() {
    return ostTrialStageId;
  }

  /**
   * Sets the value of the 'ostTrialStageId' field.
   * The stageId of the stage that should be activated.
   * @param value the value to set.
   */
  public void setOstTrialStageId(java.lang.Integer value) {
    this.ostTrialStageId = value;
  }

  /**
   * Creates a new RequestChangeOfTrialStage RecordBuilder.
   * @return A new RequestChangeOfTrialStage RecordBuilder
   */
  public static eu.driver.model.core.RequestChangeOfTrialStage.Builder newBuilder() {
    return new eu.driver.model.core.RequestChangeOfTrialStage.Builder();
  }

  /**
   * Creates a new RequestChangeOfTrialStage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RequestChangeOfTrialStage RecordBuilder
   */
  public static eu.driver.model.core.RequestChangeOfTrialStage.Builder newBuilder(eu.driver.model.core.RequestChangeOfTrialStage.Builder other) {
    return new eu.driver.model.core.RequestChangeOfTrialStage.Builder(other);
  }

  /**
   * Creates a new RequestChangeOfTrialStage RecordBuilder by copying an existing RequestChangeOfTrialStage instance.
   * @param other The existing instance to copy.
   * @return A new RequestChangeOfTrialStage RecordBuilder
   */
  public static eu.driver.model.core.RequestChangeOfTrialStage.Builder newBuilder(eu.driver.model.core.RequestChangeOfTrialStage other) {
    return new eu.driver.model.core.RequestChangeOfTrialStage.Builder(other);
  }

  /**
   * RecordBuilder for RequestChangeOfTrialStage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RequestChangeOfTrialStage>
    implements org.apache.avro.data.RecordBuilder<RequestChangeOfTrialStage> {

    /** The unique identifier of the running Trial. */
    private java.lang.Integer ostTrialId;
    /** The sessionId for the running Trial. */
    private int ostTrialSessionId;
    /** The stageId of the stage that should be activated. */
    private int ostTrialStageId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eu.driver.model.core.RequestChangeOfTrialStage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ostTrialId)) {
        this.ostTrialId = data().deepCopy(fields()[0].schema(), other.ostTrialId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ostTrialSessionId)) {
        this.ostTrialSessionId = data().deepCopy(fields()[1].schema(), other.ostTrialSessionId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ostTrialStageId)) {
        this.ostTrialStageId = data().deepCopy(fields()[2].schema(), other.ostTrialStageId);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing RequestChangeOfTrialStage instance
     * @param other The existing instance to copy.
     */
    private Builder(eu.driver.model.core.RequestChangeOfTrialStage other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.ostTrialId)) {
        this.ostTrialId = data().deepCopy(fields()[0].schema(), other.ostTrialId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ostTrialSessionId)) {
        this.ostTrialSessionId = data().deepCopy(fields()[1].schema(), other.ostTrialSessionId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ostTrialStageId)) {
        this.ostTrialStageId = data().deepCopy(fields()[2].schema(), other.ostTrialStageId);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'ostTrialId' field.
      * The unique identifier of the running Trial.
      * @return The value.
      */
    public java.lang.Integer getOstTrialId() {
      return ostTrialId;
    }

    /**
      * Sets the value of the 'ostTrialId' field.
      * The unique identifier of the running Trial.
      * @param value The value of 'ostTrialId'.
      * @return This builder.
      */
    public eu.driver.model.core.RequestChangeOfTrialStage.Builder setOstTrialId(java.lang.Integer value) {
      validate(fields()[0], value);
      this.ostTrialId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ostTrialId' field has been set.
      * The unique identifier of the running Trial.
      * @return True if the 'ostTrialId' field has been set, false otherwise.
      */
    public boolean hasOstTrialId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ostTrialId' field.
      * The unique identifier of the running Trial.
      * @return This builder.
      */
    public eu.driver.model.core.RequestChangeOfTrialStage.Builder clearOstTrialId() {
      ostTrialId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ostTrialSessionId' field.
      * The sessionId for the running Trial.
      * @return The value.
      */
    public java.lang.Integer getOstTrialSessionId() {
      return ostTrialSessionId;
    }

    /**
      * Sets the value of the 'ostTrialSessionId' field.
      * The sessionId for the running Trial.
      * @param value The value of 'ostTrialSessionId'.
      * @return This builder.
      */
    public eu.driver.model.core.RequestChangeOfTrialStage.Builder setOstTrialSessionId(int value) {
      validate(fields()[1], value);
      this.ostTrialSessionId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ostTrialSessionId' field has been set.
      * The sessionId for the running Trial.
      * @return True if the 'ostTrialSessionId' field has been set, false otherwise.
      */
    public boolean hasOstTrialSessionId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ostTrialSessionId' field.
      * The sessionId for the running Trial.
      * @return This builder.
      */
    public eu.driver.model.core.RequestChangeOfTrialStage.Builder clearOstTrialSessionId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'ostTrialStageId' field.
      * The stageId of the stage that should be activated.
      * @return The value.
      */
    public java.lang.Integer getOstTrialStageId() {
      return ostTrialStageId;
    }

    /**
      * Sets the value of the 'ostTrialStageId' field.
      * The stageId of the stage that should be activated.
      * @param value The value of 'ostTrialStageId'.
      * @return This builder.
      */
    public eu.driver.model.core.RequestChangeOfTrialStage.Builder setOstTrialStageId(int value) {
      validate(fields()[2], value);
      this.ostTrialStageId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'ostTrialStageId' field has been set.
      * The stageId of the stage that should be activated.
      * @return True if the 'ostTrialStageId' field has been set, false otherwise.
      */
    public boolean hasOstTrialStageId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'ostTrialStageId' field.
      * The stageId of the stage that should be activated.
      * @return This builder.
      */
    public eu.driver.model.core.RequestChangeOfTrialStage.Builder clearOstTrialStageId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RequestChangeOfTrialStage build() {
      try {
        RequestChangeOfTrialStage record = new RequestChangeOfTrialStage();
        record.ostTrialId = fieldSetFlags()[0] ? this.ostTrialId : (java.lang.Integer) defaultValue(fields()[0]);
        record.ostTrialSessionId = fieldSetFlags()[1] ? this.ostTrialSessionId : (java.lang.Integer) defaultValue(fields()[1]);
        record.ostTrialStageId = fieldSetFlags()[2] ? this.ostTrialStageId : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RequestChangeOfTrialStage>
    WRITER$ = (org.apache.avro.io.DatumWriter<RequestChangeOfTrialStage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RequestChangeOfTrialStage>
    READER$ = (org.apache.avro.io.DatumReader<RequestChangeOfTrialStage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
