/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.driver.model.sim.entity.item;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EnvironmentSubLabel {
  FOLIAGE, ROAD  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EnvironmentSubLabel\",\"namespace\":\"eu.driver.model.sim.entity.item\",\"symbols\":[\"FOLIAGE\",\"ROAD\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
